#!/usr/bin/env pwsh
# Banned-word gate for commit messages and PR title/body — the SINGLE source of
# truth for the LLM/AI-attribution ban. Used by BOTH:
#   - the local commit-msg hook (installed by scripts/install-hooks.ps1), and
#   - the CI gate (.github/workflows/conventional.yml).
# convco itself cannot reject words (stripRegex only edits the rendered changelog),
# so this script is the mechanical enforcement. Keep the list here in sync with the
# `stripRegex` backstop in .convco.
#
# Usage:
#   pwsh check-banned-words.ps1 -Text "<text>" [-Label "commit message"]
#   "<text>" | pwsh check-banned-words.ps1 -Label "PR body"
#   pwsh check-banned-words.ps1 -SelfTest      # run the built-in regex tests
#   pwsh check-banned-words.ps1 -ShowPattern   # print the compiled regex
# Exit code: 0 = clean, 1 = a banned token was found (or a self-test failed).

[CmdletBinding()]
param(
    [string] $Text,
    [string] $Label = 'input',
    [switch] $SelfTest,
    [switch] $ShowPattern
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- The single banned-token source -----------------------------------------
# Each entry is a regex FRAGMENT, anchored with \b word boundaries so a token can
# never trip an innocent substring: \bAI\b matches the word "AI" but NOT
# "available", "maintain", "chair" or "fail". Edit THIS list to change the policy;
# both the hook and CI read it. Matching is case-insensitive (see below), so list
# each token once in any case.
#
# Deliberately NOT banned: the bare phrases "generated with"/"generated by". Every
# real AI-attribution footer also carries a name/handle below (Claude, Copilot,
# Co-Authored-By, the robot emoji, ...), so those give full coverage WITHOUT the
# false positives a bare "generated by" would cause in a project whose own prose
# says things like "release.yml is generated by dist". (Add them back here if you
# want the stricter behaviour.)
$BannedPatterns = @(
    # Anthropic / Claude model + brand family.
    '\bClaude\b'
    '\bAnthropic\b'
    '\bOpus\b'
    '\bSonnet\b'
    '\bHaiku\b'
    '\bFable\b'
    '\bMythos\b'
    # Other LLM assistants / tools.
    '\bCopilot\b'
    '\bChatGPT\b'
    '\bGPT\b'
    # Generic AI terms. "AI" is matched CASE-SENSITIVELY (uppercase only, via the
    # inline `(?-i:...)`) so the standalone word "AI" is caught but the lowercase
    # "ai" in this repo's own `ai.github.com` SSH remote alias is NOT a false hit.
    '\bLLM\b'
    '\b(?-i:AI)\b'
    '\bA\.I\.'
    '\bartificial\s+intelligence\b'
    # Attribution trailers (the house rules forbid trailers outright anyway).
    '\bco-authored-by\b'
    '\bclaude-session\b'
    # The robot emoji U+1F916 (the literal char; the file is UTF-8). The self-test
    # below builds the same code point from its surrogate halves to prove it matches.
    '🤖'
)

$Pattern = '(' + ($BannedPatterns -join '|') + ')'
$Rx = [regex]::new($Pattern, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)

if ($ShowPattern) {
    Write-Output $Pattern
    exit 0
}

# Returns the sorted, unique set of matched tokens in $s (empty array if clean).
function Find-BannedTokens([string] $s) {
    if ([string]::IsNullOrEmpty($s)) { return @() }
    return @($Rx.Matches($s) | ForEach-Object { $_.Value } | Sort-Object -Unique)
}

if ($SelfTest) {
    # Proof that the regex rejects real attribution but passes innocent prose.
    $emoji = [char]0xD83E + [char]0xDD16
    $mustReject = @(
        'Co-Authored-By: Claude <noreply@anthropic.com>'
        'Generated with Claude Code'
        'Summary by ChatGPT and an LLM'
        'Refactored with help from Copilot'
        'use AI to classify the stream'
        'A.I. drafted this'
        'artificial intelligence assisted edit'
        'Co-authored-by: someone else'
        "$emoji Generated with a tool"
    )
    $mustPass = @(
        'available logic'
        'maintain the parser'
        'AVC High 4:4:4'
        'Add case-insensitive BDMV directory lookup'
        'Fix off-by-one in the MPLS chapter count'
        'Document how release.yml is generated by dist'
        'the report that render() produces'
        'remain available on Hawaii trails while we sail'
        'push via the ai.github.com remote alias'
        'use ai lowercase as a hostname not the acronym'
    )
    $failures = @()
    foreach ($s in $mustReject) {
        if (-not @(Find-BannedTokens $s).Count) { $failures += "should REJECT but passed: `"$s`"" }
    }
    foreach ($s in $mustPass) {
        $hit = @(Find-BannedTokens $s)
        if ($hit.Count) { $failures += "should PASS but matched [$($hit -join ', ')]: `"$s`"" }
    }
    if ($failures.Count) {
        Write-Host 'banned-word self-test FAILED:' -ForegroundColor Red
        $failures | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
        exit 1
    }
    Write-Host "banned-word self-test passed ($($mustReject.Count) reject + $($mustPass.Count) pass cases)." -ForegroundColor Green
    exit 0
}

# Normal mode: scan -Text, or stdin when -Text is absent.
if (-not $PSBoundParameters.ContainsKey('Text')) {
    $Text = [Console]::In.ReadToEnd()
}

$found = @(Find-BannedTokens $Text)
if ($found.Count) {
    Write-Host "FAILED: banned LLM/AI-attribution token(s) in ${Label}: $($found -join ', ')" -ForegroundColor Red
    Write-Host '    Remove the attribution. The policy lives in .github/scripts/check-banned-words.ps1.' -ForegroundColor DarkGray
    exit 1
}
exit 0
